# Site settings
title: Aaron Roberson
email: aaronaroberson@gmail.com
description: "Personal blog and speaking schedule of Aaron Roberson, a JavaScript and AngularJS enthusiast specializing in the development of rich internet applications with a thick front-end."
baseurl: ""
url: "http://pixelpolished.com"
twitter_link: https://twitter.com/aaronroberson
github_link:  https://github.com/aaronroberson
googleplus_link: https://plus.google.com/+AaronRoberson
linkedin_link: https://linkedin.com/in/aaronrobes

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
